/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-11-21 10:09:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.*;
import java.sql.*;
import javax.*;
import java.util.*;
import javax.servlet.*;

public final class orderSummary_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/E:/EclipseOxygenNew/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp6/wtpwebapps/MedioxyPharm/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1507560585847L));
    _jspx_dependants.put("jar:file:/E:/EclipseOxygenNew/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp6/wtpwebapps/MedioxyPharm/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("com");
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "headerContext.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <style>\r\n");
      out.write(".hidden {\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("</style> \r\n");
      out.write("    <div id=\"all\">\r\n");
      out.write("\r\n");
      out.write("        <div id=\"content\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <ul class=\"breadcrumb\">\r\n");
      out.write("                        <li><a href=\"#\">Home</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>Checkout - Order review</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-9\" id=\"checkout\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"box\" id=\"doc\">\r\n");
      out.write("                      \r\n");
      out.write("                            <h1>Order Summary</h1>\r\n");
      out.write("                            \r\n");
      out.write("\r\n");
      out.write("                            <div class=\"content\">\r\n");
      out.write("                                <div class=\"table-responsive\">\r\n");
      out.write("                                \r\n");
      out.write("                                    <table class=\"table\">\r\n");
      out.write("        ");
 
            String username=(String)session.getAttribute("username");
            Class.forName("org.h2.Driver");
            Connection con = DriverManager.getConnection("jdbc:h2:tcp://localhost/~/medioxy1","sa","");       
            Statement statement = con.createStatement();
            ResultSet resultset = statement.executeQuery("select * from Basket order by id desc limit 1 ");
           		
            
            
         
        
      out.write("\r\n");
      out.write("                                        <thead>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th>Customer Name</th>\r\n");
      out.write("                                                <th>Product ID</th>\r\n");
      out.write("                                                <th>Product Name</th>\r\n");
      out.write("                                                <th>Quantity</th>\r\n");
      out.write("                                                <th>Product price</th>\r\n");
      out.write("                                                \r\n");
      out.write("                                                <th>Total</th>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </thead>\r\n");
      out.write("                                 \r\n");
      out.write("                                      <tbody>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <!-- <td>\r\n");
      out.write("                                                    <a href=\"#\">\r\n");
      out.write("                                                        <img src=\"img/detailsquare.jpg\" alt=\"White Blouse Armani\">\r\n");
      out.write("                                                    </a>\r\n");
      out.write("                                                </td> -->\r\n");
      out.write("                                                ");
 while(resultset.next())
                                                
                                                
                                                { 
                                               
                                                
      out.write("\r\n");
      out.write("                                                \r\n");
      out.write("                                                \r\n");
      out.write("                                                <td><input type=\"hidden\" class=\"form-control\" name=\"proId\" id=\"quantity\">");
      out.print(resultset.getString("username") );
      out.write("\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td><input type=\"hidden\" class=\"form-control\" name=\"proId\" id=\"quantity\">");
      out.print(resultset.getString("proId") );
      out.write("\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td><input type=\"hidden\" class=\"form-control\" name=\"proName\" id=\"\">");
      out.print(resultset.getString("proName") );
      out.write("\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td><input type=\"hidden\" class=\"form-control\" name=\"quantity\" id=\"quantity\">");
      out.print(resultset.getString("quantity") );
      out.write("</td>\r\n");
      out.write("                                                <td><input type=\"hidden\" class=\"form-control\" name=\"proPrice\" id=\"\">Rs: ");
      out.print(resultset.getString("proPrice") );
      out.write("</td>\r\n");
      out.write("                                                \r\n");
      out.write("                                              \r\n");
      out.write("          ");

                   
                   String qtyStr = resultset.getString("quantity");
                   String priceStr = resultset.getString("proPrice");

                   String[] qtyArr = qtyStr.split(",");
                   String[] priceArr = priceStr.split(",");

                   String[] tempArr = new String[qtyArr.length];

                   String total=null;
                   int sum=0;
                   for(int i = 0; i < qtyArr.length; i++){
                   	tempArr[i] = String.valueOf(Integer.parseInt(qtyArr[i]) * Integer.parseInt(priceArr[i]));
                   	sum+=Integer.parseInt(tempArr[i]);
                   	total=String.valueOf(sum);
                   }
                   
                   
                   
                   
                   
                   
      out.write("  \r\n");
      out.write("                   \r\n");
      out.write("  <td><input type=\"hidden\" class=\"form-control\" name=\"total\" id=\"\" value=\"\">Rs:");
      out.print(total);
      out.write("</td>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("                      \r\n");
      out.write("                                            \r\n");
      out.write("   \r\n");
      out.write("                                               \r\n");
      out.write("                                          \r\n");
      out.write("                                            </tr>\r\n");
      out.write("           \r\n");
      out.write("                                        </tbody>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <tfoot>\r\n");
      out.write("                                            <!-- <tr>\r\n");
      out.write("                                                <th colspan=\"5\">Total</th>\r\n");
      out.write("                                                <th>$446.00</th>\r\n");
      out.write("                                            </tr> -->\r\n");
      out.write("                                        </tfoot>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                   \r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.table-responsive -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- /.content -->\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"box-footer\">\r\n");
      out.write("                                <div class=\"pull-left\">\r\n");
      out.write("                                    <a href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" class=\"btn btn-default\"><i class=\"fa fa-chevron-left\"></i>Back to Basket</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- <div class=\"pull-right\">\r\n");
      out.write("                                    <input type=\"submit\" class=\"btn btn-primary\" value=\"Place an order\"><i class=\"fa fa-chevron-right\"></i>\r\n");
      out.write("                                    \r\n");
      out.write("                                </div> -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                        <h3>Thank you for shopping with us.</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /.box -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <!-- /.col-md-9 -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"box\" id=\"order-summary\">\r\n");
      out.write("                        <div class=\"box-header\">\r\n");
      out.write("                            <h3>Invoice</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"text-muted\">Shipping and additional costs are calculated based on the values you have entered.</p>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"table-responsive\">\r\n");
      out.write("                            <table class=\"table\">\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>Order subtotal</td>\r\n");
      out.write("                                        <th>Rs: ");
      out.print(resultset.getString("proPrice") );
      out.write("</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>Shipping and handling</td>\r\n");
      out.write("                                        <th>Rs 0.00</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>Tax</td>\r\n");
      out.write("                                        <th>Rs 0.00</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr class=\"total\">\r\n");
      out.write("                                        <td>Total</td>\r\n");
      out.write("                                        <th>Rs: ");
      out.print(total);
      out.write("</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("                          <div class=\"box-footer\">\r\n");
      out.write("                                ");
      out.write("\r\n");
      out.write("                                 <div class=\"pull-right\">\r\n");
      out.write("                                    <input type=\"submit\" class=\"btn btn-primary\" value=\"Download\" onClick=\"window.print()\" ><i class=\"fa fa-chevron-right\"></i>\r\n");
      out.write("                                    \r\n");
      out.write("                                </div> \r\n");
      out.write("                            </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.col-md-3 -->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.container -->\r\n");
      out.write("            ");
 } 
      out.write(" \r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /#content -->\r\n");
      out.write("</form>        \r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footerContext.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/orderSummary.jsp(140,45) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/basket/${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
